spring.application.name=task_manager

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=60

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
